const ESTADOS = {
  INICIO: "INICIO",
  DISTRIBUIDORA: "DISTRIBUIDORA",
  POLIZA: "POLIZA",
  MEDIDOR: "MEDIDOR",
  ESTADO: "ESTADO",
  FOTO: "FOTO",
  COMPLETADO: "COMPLETADO"
};

module.exports = ESTADOS;
